runtime: java17
instance_class: F2

entrypoint: java -jar target/BackEnd-0.0.1-SNAPSHOT.jar

env_variables:
  SPRING_DATASOURCE_URL: jdbc:sqlserver://34.124.177.222:1433;databaseName=DuAnTotNghiepTest;encrypt=true;trustServerCertificate=true;
  SPRING_DATASOURCE_USERNAME: sqlserver
  SPRING_DATASOURCE_PASSWORD: 123s

handlers:
- url: /.*
  script: auto

beta_settings:
  cloud_sql_instances: <INSTANCE_CONNECTION_NAME>
