# Khai báo port
server: # lưu ý không được dùng tab trong file .yml 
  port: 8080
  address: 0.0.0.0
#Connect sql server
spring:
  datasource:
    #url: jdbc:sqlserver://34.124.177.222:1433;databaseName=DuAnTotNghiepTest;encrypt=true;trustServerCertificate=true;
    url: jdbc:sqlserver://localhost;databaseName=DuAnTotNghiep;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update # Hoặc create, none tuỳ theo nhu cầu
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect # Đảm bảo cung cấp dialect phù hợp  
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true
  jackson:
    serialization:
      fail-on-empty-beans: false
paypal:
  client:
    id: AbWy2B4tWfcKdb0qv6UzhoJuC2qWYpa8TwNCz-mGLynovI0bZClkwHyFyU1IEuE-KPrpZaW3Cp5avneH
    secret: EAssZAWtf6BkDmId6KYB1KrrVoxrFTWHIW7UiA_gRpAbqEy7S2_dRqjLT8zu0twefBbdPPEUDGcQDf13
  mode: sandbox # hoặc 'live' cho môi trường sản xuất
  
#url: jdbc:sqlserver://localhost;databaseName=DuAnTotNghiep;encrypt=true;trustServerCertificate=true;
