import {
  IconLayoutDashboard,
  IconTypography,
  IconHome,
  IconUsers,
  IconRectangle,
  IconBuilding,
  IconClipboardList,
  IconBrandBooking,
  IconCategory2,
  IconTruckDelivery,
  IconPhoto,
  IconShoppingCart,
  IconPackageImport,
  IconStar,
  IconBuildingWarehouse,
  IconBox,
  IconTicket,
  IconSettings,
  IconMessageDots,
  IconChecklist,
  IconAlertCircle,
} from "@tabler/icons-react";

import { uniqueId } from "lodash";

const Menuitems = [
  {
    navlabel: true,
    subheader: "Home",
  },

  {
    id: uniqueId(),
    title: "Trang chủ",
    icon: IconHome,
    href: "/dashboard",
  },
  {
    id: uniqueId(),
    title: "Dashboard",
    icon: IconLayoutDashboard,
    href: "/thongke",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý người dùng",
    icon: IconUsers,
    href: "/nguoidung",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý banner",
    icon: IconRectangle,
    href: "/banner",
    roles: ["Admin", "Nhân Viên Đăng Bài"],
  },
  {
    id: uniqueId(),
    title: "Quản lý nhà cung cấp",
    icon: IconBuilding,
    href: "/nhacungcap",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý bài đăng",
    icon: IconClipboardList,
    href: "/baidang",
    roles: ["Admin", "Nhân Viên Đăng Bài"],
  },
  {
    id: uniqueId(),
    title: "Quản lý thương hiệu",
    icon: IconBrandBooking,
    href: "/thuonghieu",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý danh mục",
    icon: IconCategory2,
    href: "/danhmuc",
    roles: ["Admin", "Nhân Viên Kho"],
  },
  {
    id: uniqueId(),
    title: "Quản lý shipper",
    icon: IconTruckDelivery,
    href: "/shipper",
    roles: ["Admin", "Nhân Viên Kho"],
  },
  {
    id: uniqueId(),
    title: "Quản lý hình ảnh",
    icon: IconPhoto,
    href: "/crudhinhAnh",
    roles: ["Admin", "Nhân Viên Kho"],
  },
  {
    id: uniqueId(),
    title: "Quản lý thương hiệu",
    icon: IconLayoutDashboard,
    href: "/thuonghieu",
    roles: ["Admin", "Nhân Viên Kho"],
  },
  {
    id: uniqueId(),
    title: "Quản lý đơn hàng",
    icon: IconShoppingCart,
    href: "/donhang",
    roles: ["Admin", "Nhân Viên Kinh Doanh"],
  },
  {
    id: uniqueId(),
    title: "Typography",
    icon: IconTypography,
    href: "/ui/typography",
    roles: ["User"],
  },
  {
    id: uniqueId(),
    title: "Quản lý nhập hàng",
    icon: IconPackageImport,
    href: "/nhaphang",
    roles: ["Nhân Viên Kho", "Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý đánh giá",
    icon: IconStar,
    href: "/danhgia",
    roles: ["Nhân Viên Kinh Doanh", "Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý kho",
    icon: IconBuildingWarehouse,
    href: "/kho",
    roles: ["Nhân Viên Kho", "Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý sản phẩm",
    icon: IconBox,
    href: "/sanpham",
    roles: ["Nhân Viên Kinh Doanh", "Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý Voucher",
    icon: IconTicket,
    href: "/voucher",
    roles: ["Nhân Viên Kinh Doanh", "Admin"],
  },
  {
    id: uniqueId(),
    title: "Settings",
    icon: IconSettings,
    href: "/settings",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Response",
    icon: IconMessageDots,
    href: "/response",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Duyệt sản phẩm",
    icon: IconChecklist,
    href: "/xetduyetsanpham",
    roles: ["Admin"],
  },
  {
    id: uniqueId(),
    title: "Quản lý popup",
    icon: IconAlertCircle,
    href: "/popup",
    roles: ["Admin", "Nhân Viên Kinh Doanh"],
  },
];

export default Menuitems;
